[package]
name = "libquickjs"
version = "1.10.0"
edition = "2024"

[features]
custom-allocator = []

[dependencies]
bitflags = "2.6"
rquickjs-sys = "0.9"

[dev-dependencies]
rquickjs-sys = { version = "0.9", features = ["bindgen", "dump-leaks"] }
